### PR TITLE
[Security]Fix ReDoS

### PR DESCRIPTION
**Pull request by ready-research**
Fix potential ReDoS

Reported in https://www.huntr.dev/bounties/bfb1fb36-b5c9-4c5a-9767-9e44644912a3

Please validate the above huntr link using the mark as valid and confirm the fix. Thank you.

### CODE REVIEW

**Comment by ready-research** [comment]
@jaywcjlove Please validate the https://www.huntr.dev/bounties/bfb1fb36-b5c9-4c5a-9767-9e44644912a3/ huntr link using the mark as valid and confirm the fix. Thank you.

**Comment by jaywcjlove** [comment]
How to mark?
@ready-research

**Comment by ready-research** [comment]
Are you able to access https://www.huntr.dev/bounties/bfb1fb36-b5c9-4c5a-9767-9e44644912a3/ using your GitHub login on the top right corner of huntr page?

**Comment by ready-research** [comment]
@jaywcjlove Thank you for your time and confirmation.

**Pull request merged**
